apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-bom-tag
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: component-bom-tag