---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/glaxman/component-cluster-autoscaler
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: component-bom
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/glaxman/component-bom
  include:
    - repository:
        name: cluster-autoscaler
      toPath: component/required/cluster-autoscaler