---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: component-provisioner
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/glaxman/component-provisioner
  include:
    - repository:
        name: cluster-autoscaler
      toPath: components/required/cluster-autoscaler